#!/usr/bin/env node
import * as fs from 'fs';
import * as path from 'path';
import * as meow from 'meow';
import { init } from './init';
import { clean } from './clean';
import { isYarnUsed, readJSON } from './util';
import * as execa from 'execa';
import { PackageJSON as PackageJson } from '@npm/types';

const packageJson = require('../../package.json') as PackageJson;
const updateNotifier = require('update-notifier').default as (
  settings: unknown
) => { notify: () => void };

export interface Logger {
  log: (...args: unknown[]) => void;
  error: (...args: unknown[]) => void;
  dir: (obj: unknown, options?: unknown) => void;
}

export interface Options {
  dryRun: boolean;
  mwtsRootDir: string;
  targetRootDir: string;
  yes: boolean;
  no: boolean;
  logger: Logger;
  yarn?: boolean;
  formatterMode?: FormatterMode;
}

export type FormatterMode = 'prettier' | 'stylistic';

export type VerbFilesFunction = (
  options: Options,
  files: string[],
  fix?: boolean
) => Promise<boolean>;

const logger: Logger = console as Logger;

const cli = meow({
  help: `
	Usage
	  $ mwts <verb> [<file>...] [options]

    Verb can be:
      init        Adds default npm scripts to your package.json.
      lint        Checks code for formatting and lint issues.
      check       Alias for lint. Kept for backward compatibility.
      fix         Fixes formatting and linting issues (if possible).
      clean       Removes all files generated by the build.

  Options
    --help        Prints this help message.
    -y, --yes     Assume a yes answer for every prompt.
    -n, --no      Assume a no answer for every prompt.
    --dry-run     Don't make any actual changes.
    --yarn        Use yarn instead of npm.
    --formatter   Formatter strategy: prettier (default) or stylistic.

	Examples
    $ mwts init -y
    $ mwts lint
    $ mwts fix
    $ mwts fix src/file1.ts src/file2.ts
    $ mwts clean`,
  flags: {
    help: { type: 'boolean' },
    yes: { type: 'boolean', alias: 'y' },
    no: { type: 'boolean', alias: 'n' },
    dryRun: { type: 'boolean' },
    yarn: { type: 'boolean' },
    formatter: { type: 'string' },
  },
});

/**
 * Get the current version of node.js being run.
 * Exported purely for stubbing purposes.
 * @private
 */
export function getNodeVersion(): string {
  return process.version;
}

export function getEslintVersion(): string {
  const packageJson = readJSON(
    require.resolve('eslint/package.json')
  ) as PackageJson;
  return packageJson.version;
}

export function getPrettierVersion(): string {
  const packageJson = readJSON(
    require.resolve('prettier/package.json')
  ) as PackageJson;
  return packageJson.version;
}

function parseFormatterMode(value: unknown): FormatterMode | undefined {
  if (value === null || value === undefined) {
    return undefined;
  }
  if (value === 'prettier' || value === 'stylistic') {
    return value;
  }
  throw new Error(
    `Unsupported formatter mode '${String(
      value
    )}'. Use 'prettier' or 'stylistic'.`
  );
}

function usage(msg?: string): void {
  if (msg) {
    logger.error(msg);
  }
  cli.showHelp(1);
}

function hasLocalEslintConfig(targetRootDir: string): boolean {
  return (
    fs.existsSync(path.join(targetRootDir, 'eslint.config.js')) ||
    fs.existsSync(path.join(targetRootDir, 'eslint.config.cjs')) ||
    fs.existsSync(path.join(targetRootDir, 'eslint.config.mjs'))
  );
}

export async function run(verb: string, files: string[]): Promise<boolean> {
  // throw if running on an old version of nodejs
  const nodeMajorVersion = Number(getNodeVersion().slice(1).split('.')[0]);
  console.log(`Node.js Version: ${nodeMajorVersion}`);
  console.log(`ESLint Version: ${getEslintVersion()}`);
  console.log(`Prettier Version: ${getPrettierVersion()}`);
  if (nodeMajorVersion < 20) {
    throw new Error(
      `mwts requires node.js 20.x or up. You are currently running
      ${process.version}, which is not supported. Please upgrade to
      a safe, secure version of nodejs!`
    );
  }

  const options = {
    dryRun: cli.flags.dryRun || false,
    // Paths are relative to the transpiled output files.
    mwtsRootDir: path.resolve(__dirname, '../..'),
    targetRootDir: process.cwd(),
    yes: cli.flags.yes || cli.flags.y || false,
    no: cli.flags.no || cli.flags.n || false,
    logger,
    yarn: cli.flags.yarn || isYarnUsed(),
    formatterMode: parseFormatterMode(cli.flags.formatter),
  } as Options;
  // Linting/formatting depend on typescript. We don't want to load the
  // typescript module during init, since it might not exist.
  // See: https://github.com/google/gts/issues/48
  if (verb === 'init') {
    return init(options);
  }

  const flags: string[] = [...files];
  if (flags.length === 0) {
    flags.push(
      '**/*.ts',
      '**/*.js',
      '**/*.tsx',
      '**/*.jsx',
      '--no-error-on-unmatched-pattern'
    );
  }

  switch (verb) {
    case 'lint':
    case 'check': {
      const eslintFlags = [...flags];
      if (!hasLocalEslintConfig(options.targetRootDir)) {
        eslintFlags.unshift(
          '--config',
          path.join(options.mwtsRootDir, 'eslint.config.js')
        );
      }
      try {
        await execa('eslint', eslintFlags, {
          stdio: 'inherit',
        });
        return true;
      } catch {
        return false;
      }
    }
    case 'fix': {
      const fixFlag = options.dryRun ? '--fix-dry-run' : '--fix';
      const eslintFlags = [fixFlag, ...flags];
      if (!hasLocalEslintConfig(options.targetRootDir)) {
        eslintFlags.unshift(
          '--config',
          path.join(options.mwtsRootDir, 'eslint.config.js')
        );
      }
      try {
        await execa('eslint', eslintFlags, {
          stdio: 'inherit',
        });
        return true;
      } catch (e) {
        console.error(e);
        return false;
      }
    }
    case 'clean':
      return clean(options);
    default:
      usage(`Unknown verb: ${verb}`);
      return false;
  }
}

updateNotifier({ pkg: packageJson }).notify();

if (cli.input.length < 1) {
  usage();
}

run(cli.input[0], cli.input.slice(1))
  .then(success => {
    if (!success) {
      process.exit(1);
    }
  })
  .catch(e => {
    console.error(e);
    process.exit(1);
  });
